"use client";

import Link from "next/link";
import {Activity, ArrowRight, CheckCircle2, FileText, GitBranch, Server, ShieldCheck} from "lucide-react";
import {clockTime, isActive, label, percent} from "@/lib/api";
import {useOperations} from "@/lib/use-operations";
import {Badge, Empty, MetricChart} from "./primitives";
import {Shell} from "./shell";

export function ResourceView({section}: {section: string}) {
  const data = useOperations();
  const latest = data.metrics.at(-1);
  const postmortems = data.incidents.filter(i => i.postmortem);
  return <Shell section={section} activeCount={data.incidents.filter(i => isActive(i.state)).length} connection={data.connection} status={data.status}>
    <div className="page-heading"><div><div className="eyebrow">OPERATIONS / {section.toUpperCase()}</div><h1>{section}</h1><p>{section === "Postmortems" ? "Verified recovery reports and actions for the next incident." : "Live operational records from configured providers."}</p></div><span className="live-label"><span className="status-dot"/>{data.connection.toUpperCase()}</span></div>
    {data.error && <div className="error-banner" role="alert">{data.error}<button onClick={() => void data.refresh()}>Retry</button></div>}
    {section === "Services" && <>{data.services.map(service => <section className="panel" key={service.id}><div className="panel-heading"><div className="heading-inline"><Server size={17}/><h2>{service.name}</h2></div><Badge value={service.healthy ? "healthy" : "degraded"}/></div><div className="resource-service"><div><span>Service ID</span><strong className="mono">{service.id}</strong></div><div><span>Region</span><strong>{service.region}</strong></div><div><span>Revision</span><strong className="mono">{service.revision}</strong></div><div><span>Error rate</span><strong>{latest ? percent(latest.error_rate) : "—"}</strong></div></div><div className="two-columns"><div><MetricChart metrics={data.metrics}/></div><div><MetricChart metrics={data.metrics} kind="latency_ms"/></div></div></section>)}<section className="panel"><div className="panel-heading"><h2>Related investigations</h2></div>{data.incidents.map(i => <Link className="resource-incident" href={`/incidents/${i.id}`} key={i.id}><span>{i.title}</span><Badge value={i.state}/><ArrowRight size={14}/></Link>)}</section></>}
    {section === "Metrics" && <div className="two-columns">{(["error_rate","latency_ms","cpu","memory","db_connections"] as const).map(kind => <section className="panel" key={kind}><div className="panel-heading"><div className="heading-inline"><Activity size={15}/><h2 className="capitalize">{label(kind)}</h2></div><span className="mono green">{latest ? kind === "latency_ms" ? `${latest[kind].toFixed(0)}ms` : percent(latest[kind]) : "—"}</span></div><MetricChart metrics={data.metrics} kind={kind}/></section>)}</div>}
    {section === "Deployments" && <section className="panel"><div className="panel-heading"><h2>Revision history</h2><span className="count-pill">{data.deployments.length}</span></div>{data.deployments.length ? [...data.deployments].reverse().map(deployment => <div className="deployment-row" key={deployment.id}><div className="deployment-icon"><GitBranch size={17}/></div><div><strong>{deployment.revision}</strong><p>{deployment.service_id} · previous revision {deployment.previous_revision}</p><div className="config-changes">{Object.entries(deployment.changes).map(([key,value]) => <span key={key} className="mono">{key}={value}</span>)}</div></div><time>{clockTime(deployment.timestamp)}</time><Badge value={deployment.healthy ? "healthy" : "degraded"}/></div>) : <Empty title="No revision events yet" description="Start the bad-deployment scenario to correlate a revision with operational degradation."/>}</section>}
    {section === "Postmortems" && <section className="panel"><div className="panel-heading"><div className="heading-inline"><FileText size={15}/><h2>Recovery reports</h2></div></div>{postmortems.length ? postmortems.map(incident => <Link className="postmortem-card" href={`/incidents/${incident.id}`} key={incident.id}><span className="mono green">INC-{incident.id.slice(0,6).toUpperCase()}</span><h3>{incident.title}</h3><p>{incident.postmortem?.summary}</p><div><CheckCircle2 size={14} className="green"/><span>Verified recovery</span><span className="mono">{clockTime(incident.postmortem?.generated_at ?? incident.updated_at)}</span><ArrowRight size={15}/></div></Link>) : <Empty title="Postmortems follow verified recovery" description="Approve the proposed remediation on an incident to complete recovery and generate the report."/>}</section>}
    {section === "System status" && <><div className="health-banner"><span className="health-icon"><ShieldCheck size={23}/></span><div><strong>{data.status?.status === "healthy" ? "Platform operating normally" : "Checking platform status"}</strong><p>Mode: {data.status?.mode ?? "connecting"} · Event stream: {data.connection}</p></div></div><section className="panel"><div className="panel-heading"><h2>Provider configuration</h2><Badge value={data.status?.mode ?? "local"}/></div>{Object.entries(data.status?.providers ?? {}).map(([name,value]) => <div className="provider-row" key={name}><span className="capitalize">{label(name)}</span><span className="mono">{value}</span><Badge value="healthy"/></div>)}</section><section className="panel"><div className="panel-heading"><h2>Verification boundaries</h2></div><div className="panel-body"><p className="muted">Local incident workflows and synthetic scenarios are exercised by automated tests. GCP adapters have mocked contract tests. Real GCP integration is {data.status?.cloud_verified ? "verified" : "awaiting cloud configuration and live verification"}.</p><p className="muted">{data.status?.subscribers ?? 0} active stream subscribers. Remediation tools are allow-listed; privileged actions require a current approval.</p></div></section></>}
  </Shell>;
}
